<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'core_string_manager' => 'get1',
);

    protected function get1()
    {
        return $this->resolveFactory(static fn() => get_string_manager(), 'core_string_manager');
    }

}
