version: "3.1"


services:
    moodle:
        build:
            dockerfile: Dockerfile 
        volumes:
            - ./app:/var/www/html/
            - ./app-data:/var/www/moodledata
            - ./php.ini-development:/usr/local/etc/php/php.ini
        ports:
            - 8088:80
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./db:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        